import Mathlib

/-! Generated by `scripts/gen_cycle.py`; do not edit by hand. -/

set_option linter.unusedVariables false
set_option linter.deprecated false

namespace GrahamPM

def fo (s p : ℕ) : ℕ :=
  if p < 1 then 0
  else   if p < 2 then 2 * s + 2
  else   if p + 6 < 2 * s then (if (p - 2) % 2 = 0 then 6 + (p - 2) / 2 else 2 * s + 1 - (p - 2) / 2)
  else   if p < 2 * s - 5 + 0 then s + 4
  else   if p < 2 * s - 5 + 1 then 3 * s + 4
  else   if p < 2 * s - 5 + 2 then s + 2
  else   if p < 2 * s - 5 + 3 then 3 * s + 3
  else   if p < 2 * s - 5 + 4 then s + 5
  else   if p < 2 * s - 5 + 5 then 3 * s + 2
  else   if p < 2 * s - 5 + 6 then s + 3
  else   if p < 2 * s - 5 + 7 then 3 * s + 1
  else   if p + 4 < 4 * s then (if (p - (2 * s + 2)) % 2 = 0 then 3 * s + 5 + (p - (2 * s + 2)) / 2 else 3 * s - (p - (2 * s + 2)) / 2)
  else   if p < 4 * s - 3 + 0 then 4
  else   if p < 4 * s - 3 + 1 then 2 * s + 3
  else   if p < 4 * s - 3 + 2 then 2
  else   if p < 4 * s - 3 + 3 then 5
  else   if p < 4 * s - 3 + 4 then 1
  else 3

lemma fo_e0 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (p < 1)) :
    fo s p = 0 := by
  unfold fo
  rw [if_pos (show p < 1 by omega)]

lemma fo_e1 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 1)) ∧ (p < 2)) :
    fo s p = 2 * s + 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_pos (show p < 2 by omega)]

lemma fo_e2 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2)) ∧ (p + 6 < 2 * s) ∧ ((p - 2) % 2 = 0)) :
    fo s p = 6 + (p - 2) / 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_pos (show p + 6 < 2 * s by omega), if_pos (show (p - 2) % 2 = 0 by omega)]

lemma fo_e3 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2)) ∧ (p + 6 < 2 * s) ∧ (¬ ((p - 2) % 2 = 0))) :
    fo s p = 2 * s + 1 - (p - 2) / 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_pos (show p + 6 < 2 * s by omega), if_neg (show ¬ ((p - 2) % 2 = 0) by omega)]

lemma fo_e4 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p + 6 < 2 * s)) ∧ (p < 2 * s - 5 + 0)) :
    fo s p = s + 4 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_pos (show p < 2 * s - 5 + 0 by omega)]

lemma fo_e5 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 0)) ∧ (p < 2 * s - 5 + 1)) :
    fo s p = 3 * s + 4 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_pos (show p < 2 * s - 5 + 1 by omega)]

lemma fo_e6 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 1)) ∧ (p < 2 * s - 5 + 2)) :
    fo s p = s + 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_pos (show p < 2 * s - 5 + 2 by omega)]

lemma fo_e7 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 2)) ∧ (p < 2 * s - 5 + 3)) :
    fo s p = 3 * s + 3 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_pos (show p < 2 * s - 5 + 3 by omega)]

lemma fo_e8 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 3)) ∧ (p < 2 * s - 5 + 4)) :
    fo s p = s + 5 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_pos (show p < 2 * s - 5 + 4 by omega)]

lemma fo_e9 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 4)) ∧ (p < 2 * s - 5 + 5)) :
    fo s p = 3 * s + 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_pos (show p < 2 * s - 5 + 5 by omega)]

lemma fo_e10 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 5)) ∧ (p < 2 * s - 5 + 6)) :
    fo s p = s + 3 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_pos (show p < 2 * s - 5 + 6 by omega)]

lemma fo_e11 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 6)) ∧ (p < 2 * s - 5 + 7)) :
    fo s p = 3 * s + 1 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_pos (show p < 2 * s - 5 + 7 by omega)]

lemma fo_e12 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 7)) ∧ (p + 4 < 4 * s) ∧ ((p - (2 * s + 2)) % 2 = 0)) :
    fo s p = 3 * s + 5 + (p - (2 * s + 2)) / 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_pos (show p + 4 < 4 * s by omega), if_pos (show (p - (2 * s + 2)) % 2 = 0 by omega)]

lemma fo_e13 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 7)) ∧ (p + 4 < 4 * s) ∧ (¬ ((p - (2 * s + 2)) % 2 = 0))) :
    fo s p = 3 * s - (p - (2 * s + 2)) / 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_pos (show p + 4 < 4 * s by omega), if_neg (show ¬ ((p - (2 * s + 2)) % 2 = 0) by omega)]

lemma fo_e14 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p + 4 < 4 * s)) ∧ (p < 4 * s - 3 + 0)) :
    fo s p = 4 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_neg (show ¬ (p + 4 < 4 * s) by omega), if_pos (show p < 4 * s - 3 + 0 by omega)]

lemma fo_e15 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 3 + 0)) ∧ (p < 4 * s - 3 + 1)) :
    fo s p = 2 * s + 3 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_neg (show ¬ (p + 4 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 3 + 0) by omega), if_pos (show p < 4 * s - 3 + 1 by omega)]

lemma fo_e16 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 3 + 1)) ∧ (p < 4 * s - 3 + 2)) :
    fo s p = 2 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_neg (show ¬ (p + 4 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 3 + 0) by omega), if_neg (show ¬ (p < 4 * s - 3 + 1) by omega), if_pos (show p < 4 * s - 3 + 2 by omega)]

lemma fo_e17 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 3 + 2)) ∧ (p < 4 * s - 3 + 3)) :
    fo s p = 5 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_neg (show ¬ (p + 4 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 3 + 0) by omega), if_neg (show ¬ (p < 4 * s - 3 + 1) by omega), if_neg (show ¬ (p < 4 * s - 3 + 2) by omega), if_pos (show p < 4 * s - 3 + 3 by omega)]

lemma fo_e18 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 3 + 3)) ∧ (p < 4 * s - 3 + 4)) :
    fo s p = 1 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_neg (show ¬ (p + 4 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 3 + 0) by omega), if_neg (show ¬ (p < 4 * s - 3 + 1) by omega), if_neg (show ¬ (p < 4 * s - 3 + 2) by omega), if_neg (show ¬ (p < 4 * s - 3 + 3) by omega), if_pos (show p < 4 * s - 3 + 4 by omega)]

lemma fo_e19 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 3 + 4))) :
    fo s p = 3 := by
  unfold fo
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s - 5 + 7) by omega), if_neg (show ¬ (p + 4 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 3 + 0) by omega), if_neg (show ¬ (p < 4 * s - 3 + 1) by omega), if_neg (show ¬ (p < 4 * s - 3 + 2) by omega), if_neg (show ¬ (p < 4 * s - 3 + 3) by omega), if_neg (show ¬ (p < 4 * s - 3 + 4) by omega)]

lemma fo_seg {s : ℕ} (p : ℕ) (hh : 5 ≤ s) :
    ((p < 1)) ∨
    ((¬ (p < 1)) ∧ (p < 2)) ∨
    ((¬ (p < 2)) ∧ (p + 6 < 2 * s) ∧ ((p - 2) % 2 = 0)) ∨
    ((¬ (p < 2)) ∧ (p + 6 < 2 * s) ∧ (¬ ((p - 2) % 2 = 0))) ∨
    ((¬ (p + 6 < 2 * s)) ∧ (p < 2 * s - 5 + 0)) ∨
    ((¬ (p < 2 * s - 5 + 0)) ∧ (p < 2 * s - 5 + 1)) ∨
    ((¬ (p < 2 * s - 5 + 1)) ∧ (p < 2 * s - 5 + 2)) ∨
    ((¬ (p < 2 * s - 5 + 2)) ∧ (p < 2 * s - 5 + 3)) ∨
    ((¬ (p < 2 * s - 5 + 3)) ∧ (p < 2 * s - 5 + 4)) ∨
    ((¬ (p < 2 * s - 5 + 4)) ∧ (p < 2 * s - 5 + 5)) ∨
    ((¬ (p < 2 * s - 5 + 5)) ∧ (p < 2 * s - 5 + 6)) ∨
    ((¬ (p < 2 * s - 5 + 6)) ∧ (p < 2 * s - 5 + 7)) ∨
    ((¬ (p < 2 * s - 5 + 7)) ∧ (p + 4 < 4 * s) ∧ ((p - (2 * s + 2)) % 2 = 0)) ∨
    ((¬ (p < 2 * s - 5 + 7)) ∧ (p + 4 < 4 * s) ∧ (¬ ((p - (2 * s + 2)) % 2 = 0))) ∨
    ((¬ (p + 4 < 4 * s)) ∧ (p < 4 * s - 3 + 0)) ∨
    ((¬ (p < 4 * s - 3 + 0)) ∧ (p < 4 * s - 3 + 1)) ∨
    ((¬ (p < 4 * s - 3 + 1)) ∧ (p < 4 * s - 3 + 2)) ∨
    ((¬ (p < 4 * s - 3 + 2)) ∧ (p < 4 * s - 3 + 3)) ∨
    ((¬ (p < 4 * s - 3 + 3)) ∧ (p < 4 * s - 3 + 4)) ∨
    ((¬ (p < 4 * s - 3 + 4))) := by
  omega

-- number of pieces of `fo`: 20

def dso (s p : ℕ) : ℤ :=
  if p < 1 then 2 * (s : ℤ) + 2
  else   if p < 2 then -(2 * (s : ℤ) - 4)
  else   if p + 7 < 2 * s then (if (p - 2) % 2 = 0 then 2 * (s : ℤ) - 5 - ((p : ℤ) - 2) else -(2 * (s : ℤ) - 5 - ((p : ℤ) - 2)))
  else   if p + 6 < 2 * s then -2
  else   if p < 2 * s - 5 + 0 then 2 * (s : ℤ)
  else   if p < 2 * s - 5 + 1 then -(2 * (s : ℤ) + 2)
  else   if p < 2 * s - 5 + 2 then 2 * (s : ℤ) + 1
  else   if p < 2 * s - 5 + 3 then -(2 * (s : ℤ) - 2)
  else   if p < 2 * s - 5 + 4 then 2 * (s : ℤ) - 3
  else   if p < 2 * s - 5 + 5 then -(2 * (s : ℤ) - 1)
  else   if p < 2 * s - 5 + 6 then 2 * (s : ℤ) - 2
  else   if p < 2 * s + 2 then 4
  else   if p + 5 < 4 * s then (if (p - (2 * s + 2)) % 2 = 0 then -(5 + ((p : ℤ) - (2 * (s : ℤ) + 2))) else 5 + ((p : ℤ) - (2 * (s : ℤ) + 2)))
  else   if p < 4 * s - 4 + 0 then -(2 * (s : ℤ))
  else   if p < 4 * s - 4 + 1 then 2 * (s : ℤ) - 1
  else   if p < 4 * s - 4 + 2 then -(2 * (s : ℤ) + 1)
  else   if p < 4 * s - 4 + 3 then 3
  else   if p < 4 * s - 4 + 4 then -4
  else   if p < 4 * s - 4 + 5 then 2
  else -3

lemma dso_e0 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (p < 1)) :
    dso s p = 2 * (s : ℤ) + 2 := by
  unfold dso
  rw [if_pos (show p < 1 by omega)]

lemma dso_e1 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 1)) ∧ (p < 2)) :
    dso s p = -(2 * (s : ℤ) - 4) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_pos (show p < 2 by omega)]

lemma dso_e2 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2)) ∧ (p + 7 < 2 * s) ∧ ((p - 2) % 2 = 0)) :
    dso s p = 2 * (s : ℤ) - 5 - ((p : ℤ) - 2) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_pos (show p + 7 < 2 * s by omega), if_pos (show (p - 2) % 2 = 0 by omega)]

lemma dso_e3 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2)) ∧ (p + 7 < 2 * s) ∧ (¬ ((p - 2) % 2 = 0))) :
    dso s p = -(2 * (s : ℤ) - 5 - ((p : ℤ) - 2)) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_pos (show p + 7 < 2 * s by omega), if_neg (show ¬ ((p - 2) % 2 = 0) by omega)]

lemma dso_e4 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p + 7 < 2 * s)) ∧ (p + 6 < 2 * s)) :
    dso s p = -2 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_pos (show p + 6 < 2 * s by omega)]

lemma dso_e5 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p + 6 < 2 * s)) ∧ (p < 2 * s - 5 + 0)) :
    dso s p = 2 * (s : ℤ) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_pos (show p < 2 * s - 5 + 0 by omega)]

lemma dso_e6 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 0)) ∧ (p < 2 * s - 5 + 1)) :
    dso s p = -(2 * (s : ℤ) + 2) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_pos (show p < 2 * s - 5 + 1 by omega)]

lemma dso_e7 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 1)) ∧ (p < 2 * s - 5 + 2)) :
    dso s p = 2 * (s : ℤ) + 1 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_pos (show p < 2 * s - 5 + 2 by omega)]

lemma dso_e8 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 2)) ∧ (p < 2 * s - 5 + 3)) :
    dso s p = -(2 * (s : ℤ) - 2) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_pos (show p < 2 * s - 5 + 3 by omega)]

lemma dso_e9 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 3)) ∧ (p < 2 * s - 5 + 4)) :
    dso s p = 2 * (s : ℤ) - 3 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_pos (show p < 2 * s - 5 + 4 by omega)]

lemma dso_e10 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 4)) ∧ (p < 2 * s - 5 + 5)) :
    dso s p = -(2 * (s : ℤ) - 1) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_pos (show p < 2 * s - 5 + 5 by omega)]

lemma dso_e11 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 5)) ∧ (p < 2 * s - 5 + 6)) :
    dso s p = 2 * (s : ℤ) - 2 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_pos (show p < 2 * s - 5 + 6 by omega)]

lemma dso_e12 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s - 5 + 6)) ∧ (p < 2 * s + 2)) :
    dso s p = 4 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_pos (show p < 2 * s + 2 by omega)]

lemma dso_e13 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s + 2)) ∧ (p + 5 < 4 * s) ∧ ((p - (2 * s + 2)) % 2 = 0)) :
    dso s p = -(5 + ((p : ℤ) - (2 * (s : ℤ) + 2))) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_pos (show p + 5 < 4 * s by omega), if_pos (show (p - (2 * s + 2)) % 2 = 0 by omega)]

lemma dso_e14 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 2 * s + 2)) ∧ (p + 5 < 4 * s) ∧ (¬ ((p - (2 * s + 2)) % 2 = 0))) :
    dso s p = 5 + ((p : ℤ) - (2 * (s : ℤ) + 2)) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_pos (show p + 5 < 4 * s by omega), if_neg (show ¬ ((p - (2 * s + 2)) % 2 = 0) by omega)]

lemma dso_e15 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p + 5 < 4 * s)) ∧ (p < 4 * s - 4 + 0)) :
    dso s p = -(2 * (s : ℤ)) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_neg (show ¬ (p + 5 < 4 * s) by omega), if_pos (show p < 4 * s - 4 + 0 by omega)]

lemma dso_e16 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 4 + 0)) ∧ (p < 4 * s - 4 + 1)) :
    dso s p = 2 * (s : ℤ) - 1 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_neg (show ¬ (p + 5 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 4 + 0) by omega), if_pos (show p < 4 * s - 4 + 1 by omega)]

lemma dso_e17 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 4 + 1)) ∧ (p < 4 * s - 4 + 2)) :
    dso s p = -(2 * (s : ℤ) + 1) := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_neg (show ¬ (p + 5 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 4 + 0) by omega), if_neg (show ¬ (p < 4 * s - 4 + 1) by omega), if_pos (show p < 4 * s - 4 + 2 by omega)]

lemma dso_e18 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 4 + 2)) ∧ (p < 4 * s - 4 + 3)) :
    dso s p = 3 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_neg (show ¬ (p + 5 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 4 + 0) by omega), if_neg (show ¬ (p < 4 * s - 4 + 1) by omega), if_neg (show ¬ (p < 4 * s - 4 + 2) by omega), if_pos (show p < 4 * s - 4 + 3 by omega)]

lemma dso_e19 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 4 + 3)) ∧ (p < 4 * s - 4 + 4)) :
    dso s p = -4 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_neg (show ¬ (p + 5 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 4 + 0) by omega), if_neg (show ¬ (p < 4 * s - 4 + 1) by omega), if_neg (show ¬ (p < 4 * s - 4 + 2) by omega), if_neg (show ¬ (p < 4 * s - 4 + 3) by omega), if_pos (show p < 4 * s - 4 + 4 by omega)]

lemma dso_e20 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 4 + 4)) ∧ (p < 4 * s - 4 + 5)) :
    dso s p = 2 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_neg (show ¬ (p + 5 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 4 + 0) by omega), if_neg (show ¬ (p < 4 * s - 4 + 1) by omega), if_neg (show ¬ (p < 4 * s - 4 + 2) by omega), if_neg (show ¬ (p < 4 * s - 4 + 3) by omega), if_neg (show ¬ (p < 4 * s - 4 + 4) by omega), if_pos (show p < 4 * s - 4 + 5 by omega)]

lemma dso_e21 {s : ℕ} (p : ℕ) (hh : 5 ≤ s) (hs : (¬ (p < 4 * s - 4 + 5))) :
    dso s p = -3 := by
  unfold dso
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p + 7 < 2 * s) by omega), if_neg (show ¬ (p + 6 < 2 * s) by omega), if_neg (show ¬ (p < 2 * s - 5 + 0) by omega), if_neg (show ¬ (p < 2 * s - 5 + 1) by omega), if_neg (show ¬ (p < 2 * s - 5 + 2) by omega), if_neg (show ¬ (p < 2 * s - 5 + 3) by omega), if_neg (show ¬ (p < 2 * s - 5 + 4) by omega), if_neg (show ¬ (p < 2 * s - 5 + 5) by omega), if_neg (show ¬ (p < 2 * s - 5 + 6) by omega), if_neg (show ¬ (p < 2 * s + 2) by omega), if_neg (show ¬ (p + 5 < 4 * s) by omega), if_neg (show ¬ (p < 4 * s - 4 + 0) by omega), if_neg (show ¬ (p < 4 * s - 4 + 1) by omega), if_neg (show ¬ (p < 4 * s - 4 + 2) by omega), if_neg (show ¬ (p < 4 * s - 4 + 3) by omega), if_neg (show ¬ (p < 4 * s - 4 + 4) by omega), if_neg (show ¬ (p < 4 * s - 4 + 5) by omega)]

lemma dso_seg {s : ℕ} (p : ℕ) (hh : 5 ≤ s) :
    ((p < 1)) ∨
    ((¬ (p < 1)) ∧ (p < 2)) ∨
    ((¬ (p < 2)) ∧ (p + 7 < 2 * s) ∧ ((p - 2) % 2 = 0)) ∨
    ((¬ (p < 2)) ∧ (p + 7 < 2 * s) ∧ (¬ ((p - 2) % 2 = 0))) ∨
    ((¬ (p + 7 < 2 * s)) ∧ (p + 6 < 2 * s)) ∨
    ((¬ (p + 6 < 2 * s)) ∧ (p < 2 * s - 5 + 0)) ∨
    ((¬ (p < 2 * s - 5 + 0)) ∧ (p < 2 * s - 5 + 1)) ∨
    ((¬ (p < 2 * s - 5 + 1)) ∧ (p < 2 * s - 5 + 2)) ∨
    ((¬ (p < 2 * s - 5 + 2)) ∧ (p < 2 * s - 5 + 3)) ∨
    ((¬ (p < 2 * s - 5 + 3)) ∧ (p < 2 * s - 5 + 4)) ∨
    ((¬ (p < 2 * s - 5 + 4)) ∧ (p < 2 * s - 5 + 5)) ∨
    ((¬ (p < 2 * s - 5 + 5)) ∧ (p < 2 * s - 5 + 6)) ∨
    ((¬ (p < 2 * s - 5 + 6)) ∧ (p < 2 * s + 2)) ∨
    ((¬ (p < 2 * s + 2)) ∧ (p + 5 < 4 * s) ∧ ((p - (2 * s + 2)) % 2 = 0)) ∨
    ((¬ (p < 2 * s + 2)) ∧ (p + 5 < 4 * s) ∧ (¬ ((p - (2 * s + 2)) % 2 = 0))) ∨
    ((¬ (p + 5 < 4 * s)) ∧ (p < 4 * s - 4 + 0)) ∨
    ((¬ (p < 4 * s - 4 + 0)) ∧ (p < 4 * s - 4 + 1)) ∨
    ((¬ (p < 4 * s - 4 + 1)) ∧ (p < 4 * s - 4 + 2)) ∨
    ((¬ (p < 4 * s - 4 + 2)) ∧ (p < 4 * s - 4 + 3)) ∨
    ((¬ (p < 4 * s - 4 + 3)) ∧ (p < 4 * s - 4 + 4)) ∨
    ((¬ (p < 4 * s - 4 + 4)) ∧ (p < 4 * s - 4 + 5)) ∨
    ((¬ (p < 4 * s - 4 + 5))) := by
  omega

-- number of pieces of `dso`: 22

set_option maxHeartbeats 8000000 in
lemma fo_lt {s p : ℕ} (hh : 5 ≤ s) (hp : p < 4 * s + 2) : fo s p < 4 * s + 2 := by
  rcases fo_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> (first | rw [fo_e0 p hh hs] | rw [fo_e1 p hh hs] | rw [fo_e2 p hh hs] | rw [fo_e3 p hh hs] | rw [fo_e4 p hh hs] | rw [fo_e5 p hh hs] | rw [fo_e6 p hh hs] | rw [fo_e7 p hh hs] | rw [fo_e8 p hh hs] | rw [fo_e9 p hh hs] | rw [fo_e10 p hh hs] | rw [fo_e11 p hh hs] | rw [fo_e12 p hh hs] | rw [fo_e13 p hh hs] | rw [fo_e14 p hh hs] | rw [fo_e15 p hh hs] | rw [fo_e16 p hh hs] | rw [fo_e17 p hh hs] | rw [fo_e18 p hh hs] | rw [fo_e19 p hh hs]) <;> omega

set_option maxHeartbeats 8000000 in
lemma fo_inj {s p q : ℕ} (hh : 5 ≤ s) (hp : p < 4 * s + 2) (hq : q < 4 * s + 2)
    (he : fo s p = fo s q) : p = q := by
  rcases fo_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> rcases fo_seg q hh with ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht <;>
  (first | rw [fo_e0 p hh hs] at he | rw [fo_e1 p hh hs] at he | rw [fo_e2 p hh hs] at he | rw [fo_e3 p hh hs] at he | rw [fo_e4 p hh hs] at he | rw [fo_e5 p hh hs] at he | rw [fo_e6 p hh hs] at he | rw [fo_e7 p hh hs] at he | rw [fo_e8 p hh hs] at he | rw [fo_e9 p hh hs] at he | rw [fo_e10 p hh hs] at he | rw [fo_e11 p hh hs] at he | rw [fo_e12 p hh hs] at he | rw [fo_e13 p hh hs] at he | rw [fo_e14 p hh hs] at he | rw [fo_e15 p hh hs] at he | rw [fo_e16 p hh hs] at he | rw [fo_e17 p hh hs] at he | rw [fo_e18 p hh hs] at he | rw [fo_e19 p hh hs] at he) <;>
  (first | rw [fo_e0 q hh ht] at he | rw [fo_e1 q hh ht] at he | rw [fo_e2 q hh ht] at he | rw [fo_e3 q hh ht] at he | rw [fo_e4 q hh ht] at he | rw [fo_e5 q hh ht] at he | rw [fo_e6 q hh ht] at he | rw [fo_e7 q hh ht] at he | rw [fo_e8 q hh ht] at he | rw [fo_e9 q hh ht] at he | rw [fo_e10 q hh ht] at he | rw [fo_e11 q hh ht] at he | rw [fo_e12 q hh ht] at he | rw [fo_e13 q hh ht] at he | rw [fo_e14 q hh ht] at he | rw [fo_e15 q hh ht] at he | rw [fo_e16 q hh ht] at he | rw [fo_e17 q hh ht] at he | rw [fo_e18 q hh ht] at he | rw [fo_e19 q hh ht] at he) <;> omega

set_option maxHeartbeats 8000000 in
lemma dso_range {s p : ℕ} (hh : 5 ≤ s) (hp : p < 4 * s + 2) :
    (2 ≤ dso s p ∧ dso s p ≤ 2 * (s : ℤ) + 2) ∨ (-(2 * (s : ℤ) + 2) ≤ dso s p ∧ dso s p ≤ -2) := by
  rcases dso_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> (first | rw [dso_e0 p hh hs] | rw [dso_e1 p hh hs] | rw [dso_e2 p hh hs] | rw [dso_e3 p hh hs] | rw [dso_e4 p hh hs] | rw [dso_e5 p hh hs] | rw [dso_e6 p hh hs] | rw [dso_e7 p hh hs] | rw [dso_e8 p hh hs] | rw [dso_e9 p hh hs] | rw [dso_e10 p hh hs] | rw [dso_e11 p hh hs] | rw [dso_e12 p hh hs] | rw [dso_e13 p hh hs] | rw [dso_e14 p hh hs] | rw [dso_e15 p hh hs] | rw [dso_e16 p hh hs] | rw [dso_e17 p hh hs] | rw [dso_e18 p hh hs] | rw [dso_e19 p hh hs] | rw [dso_e20 p hh hs] | rw [dso_e21 p hh hs]) <;> omega

set_option maxHeartbeats 8000000 in
lemma dso_inj {s p q : ℕ} (hh : 5 ≤ s) (hp : p < 4 * s + 2) (hq : q < 4 * s + 2)
    (he : dso s p = dso s q) : p = q := by
  rcases dso_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> rcases dso_seg q hh with ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht <;>
  (first | rw [dso_e0 p hh hs] at he | rw [dso_e1 p hh hs] at he | rw [dso_e2 p hh hs] at he | rw [dso_e3 p hh hs] at he | rw [dso_e4 p hh hs] at he | rw [dso_e5 p hh hs] at he | rw [dso_e6 p hh hs] at he | rw [dso_e7 p hh hs] at he | rw [dso_e8 p hh hs] at he | rw [dso_e9 p hh hs] at he | rw [dso_e10 p hh hs] at he | rw [dso_e11 p hh hs] at he | rw [dso_e12 p hh hs] at he | rw [dso_e13 p hh hs] at he | rw [dso_e14 p hh hs] at he | rw [dso_e15 p hh hs] at he | rw [dso_e16 p hh hs] at he | rw [dso_e17 p hh hs] at he | rw [dso_e18 p hh hs] at he | rw [dso_e19 p hh hs] at he | rw [dso_e20 p hh hs] at he | rw [dso_e21 p hh hs] at he) <;>
  (first | rw [dso_e0 q hh ht] at he | rw [dso_e1 q hh ht] at he | rw [dso_e2 q hh ht] at he | rw [dso_e3 q hh ht] at he | rw [dso_e4 q hh ht] at he | rw [dso_e5 q hh ht] at he | rw [dso_e6 q hh ht] at he | rw [dso_e7 q hh ht] at he | rw [dso_e8 q hh ht] at he | rw [dso_e9 q hh ht] at he | rw [dso_e10 q hh ht] at he | rw [dso_e11 q hh ht] at he | rw [dso_e12 q hh ht] at he | rw [dso_e13 q hh ht] at he | rw [dso_e14 q hh ht] at he | rw [dso_e15 q hh ht] at he | rw [dso_e16 q hh ht] at he | rw [dso_e17 q hh ht] at he | rw [dso_e18 q hh ht] at he | rw [dso_e19 q hh ht] at he | rw [dso_e20 q hh ht] at he | rw [dso_e21 q hh ht] at he) <;> omega

set_option maxHeartbeats 8000000 in
lemma fo_step {s p : ℕ} (hh : 5 ≤ s) (hp : p + 1 < 4 * s + 2) :
    (fo s (p + 1) : ℤ) = fo s p + dso s p := by
  rcases dso_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> (first | rw [dso_e0 p hh hs] | rw [dso_e1 p hh hs] | rw [dso_e2 p hh hs] | rw [dso_e3 p hh hs] | rw [dso_e4 p hh hs] | rw [dso_e5 p hh hs] | rw [dso_e6 p hh hs] | rw [dso_e7 p hh hs] | rw [dso_e8 p hh hs] | rw [dso_e9 p hh hs] | rw [dso_e10 p hh hs] | rw [dso_e11 p hh hs] | rw [dso_e12 p hh hs] | rw [dso_e13 p hh hs] | rw [dso_e14 p hh hs] | rw [dso_e15 p hh hs] | rw [dso_e16 p hh hs] | rw [dso_e17 p hh hs] | rw [dso_e18 p hh hs] | rw [dso_e19 p hh hs] | rw [dso_e20 p hh hs] | rw [dso_e21 p hh hs]) <;>
  (first | rw [fo_e0 p hh (by omega)] | rw [fo_e1 p hh (by omega)] | rw [fo_e2 p hh (by omega)] | rw [fo_e3 p hh (by omega)] | rw [fo_e4 p hh (by omega)] | rw [fo_e5 p hh (by omega)] | rw [fo_e6 p hh (by omega)] | rw [fo_e7 p hh (by omega)] | rw [fo_e8 p hh (by omega)] | rw [fo_e9 p hh (by omega)] | rw [fo_e10 p hh (by omega)] | rw [fo_e11 p hh (by omega)] | rw [fo_e12 p hh (by omega)] | rw [fo_e13 p hh (by omega)] | rw [fo_e14 p hh (by omega)] | rw [fo_e15 p hh (by omega)] | rw [fo_e16 p hh (by omega)] | rw [fo_e17 p hh (by omega)] | rw [fo_e18 p hh (by omega)] | rw [fo_e19 p hh (by omega)]) <;>
  (first | rw [fo_e0 (p + 1) hh (by omega)] | rw [fo_e1 (p + 1) hh (by omega)] | rw [fo_e2 (p + 1) hh (by omega)] | rw [fo_e3 (p + 1) hh (by omega)] | rw [fo_e4 (p + 1) hh (by omega)] | rw [fo_e5 (p + 1) hh (by omega)] | rw [fo_e6 (p + 1) hh (by omega)] | rw [fo_e7 (p + 1) hh (by omega)] | rw [fo_e8 (p + 1) hh (by omega)] | rw [fo_e9 (p + 1) hh (by omega)] | rw [fo_e10 (p + 1) hh (by omega)] | rw [fo_e11 (p + 1) hh (by omega)] | rw [fo_e12 (p + 1) hh (by omega)] | rw [fo_e13 (p + 1) hh (by omega)] | rw [fo_e14 (p + 1) hh (by omega)] | rw [fo_e15 (p + 1) hh (by omega)] | rw [fo_e16 (p + 1) hh (by omega)] | rw [fo_e17 (p + 1) hh (by omega)] | rw [fo_e18 (p + 1) hh (by omega)] | rw [fo_e19 (p + 1) hh (by omega)]) <;> omega

set_option maxHeartbeats 8000000 in
lemma fo_last {s : ℕ} (hh : 5 ≤ s) :
    (fo s 0 : ℤ) = fo s (4 * s + 2 - 1) + dso s (4 * s + 2 - 1) := by
  (first | rw [dso_e0 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e1 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e2 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e3 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e4 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e5 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e6 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e7 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e8 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e9 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e10 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e11 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e12 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e13 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e14 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e15 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e16 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e17 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e18 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e19 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e20 (4 * s + 2 - 1) hh (by omega)] | rw [dso_e21 (4 * s + 2 - 1) hh (by omega)])
  (first | rw [fo_e0 0 hh (by omega)] | rw [fo_e1 0 hh (by omega)] | rw [fo_e2 0 hh (by omega)] | rw [fo_e3 0 hh (by omega)] | rw [fo_e4 0 hh (by omega)] | rw [fo_e5 0 hh (by omega)] | rw [fo_e6 0 hh (by omega)] | rw [fo_e7 0 hh (by omega)] | rw [fo_e8 0 hh (by omega)] | rw [fo_e9 0 hh (by omega)] | rw [fo_e10 0 hh (by omega)] | rw [fo_e11 0 hh (by omega)] | rw [fo_e12 0 hh (by omega)] | rw [fo_e13 0 hh (by omega)] | rw [fo_e14 0 hh (by omega)] | rw [fo_e15 0 hh (by omega)] | rw [fo_e16 0 hh (by omega)] | rw [fo_e17 0 hh (by omega)] | rw [fo_e18 0 hh (by omega)] | rw [fo_e19 0 hh (by omega)])
  (first | rw [fo_e0 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e1 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e2 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e3 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e4 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e5 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e6 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e7 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e8 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e9 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e10 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e11 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e12 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e13 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e14 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e15 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e16 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e17 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e18 (4 * s + 2 - 1) hh (by omega)] | rw [fo_e19 (4 * s + 2 - 1) hh (by omega)])
  omega

end GrahamPM
