import Mathlib

/-! Generated by `scripts/gen_cycle.py`; do not edit by hand. -/

set_option linter.unusedVariables false
set_option linter.deprecated false

namespace GrahamPM

def fe (h p : ℕ) : ℕ :=
  if p < 1 then 0
  else   if p < 2 then 5
  else   if p < 3 then 1
  else   if p < 4 then 4
  else   if p < 5 then 2 * h + 1
  else   if p + 3 < 2 * h then (if (p - 5) % 2 = 0 then 6 + (p - 5) / 2 else 2 * h - (p - 5) / 2)
  else   if p + 2 < 2 * h then 3 * h + 1
  else   if p + 1 < 2 * h then 3 * h - 1
  else   if p < 2 * h then h + 2
  else   if p < 2 * h + 1 then 3 * h
  else   if p < 2 * h + 2 then 3 * h + 2
  else   if p < 2 * h + 3 then h + 4
  else   if p < 2 * h + 4 then 3 * h + 3
  else   if p < 2 * h + 5 then h + 3
  else   if p + 5 < 4 * h then (if (p - (2 * h + 5)) % 2 = 0 then 3 * h + 4 + (p - (2 * h + 5)) / 2 else 3 * h - 2 - (p - (2 * h + 5)) / 2)
  else   if p + 4 < 4 * h then 4 * h - 1
  else   if p + 3 < 4 * h then 2 * h + 3
  else   if p + 2 < 4 * h then 2
  else   if p + 1 < 4 * h then 2 * h + 2
  else 3

lemma fe_e0 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (p < 1)) :
    fe h p = 0 := by
  unfold fe
  rw [if_pos (show p < 1 by omega)]

lemma fe_e1 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 1)) ∧ (p < 2)) :
    fe h p = 5 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_pos (show p < 2 by omega)]

lemma fe_e2 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2)) ∧ (p < 3)) :
    fe h p = 1 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_pos (show p < 3 by omega)]

lemma fe_e3 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 3)) ∧ (p < 4)) :
    fe h p = 4 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_pos (show p < 4 by omega)]

lemma fe_e4 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 4)) ∧ (p < 5)) :
    fe h p = 2 * h + 1 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_pos (show p < 5 by omega)]

lemma fe_e5 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 5)) ∧ (p + 3 < 2 * h) ∧ ((p - 5) % 2 = 0)) :
    fe h p = 6 + (p - 5) / 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_pos (show p + 3 < 2 * h by omega), if_pos (show (p - 5) % 2 = 0 by omega)]

lemma fe_e6 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 5)) ∧ (p + 3 < 2 * h) ∧ (¬ ((p - 5) % 2 = 0))) :
    fe h p = 2 * h - (p - 5) / 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_pos (show p + 3 < 2 * h by omega), if_neg (show ¬ ((p - 5) % 2 = 0) by omega)]

lemma fe_e7 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 3 < 2 * h)) ∧ (p + 2 < 2 * h)) :
    fe h p = 3 * h + 1 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_pos (show p + 2 < 2 * h by omega)]

lemma fe_e8 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 2 < 2 * h)) ∧ (p + 1 < 2 * h)) :
    fe h p = 3 * h - 1 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_pos (show p + 1 < 2 * h by omega)]

lemma fe_e9 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 1 < 2 * h)) ∧ (p < 2 * h)) :
    fe h p = h + 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_pos (show p < 2 * h by omega)]

lemma fe_e10 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h)) ∧ (p < 2 * h + 1)) :
    fe h p = 3 * h := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_pos (show p < 2 * h + 1 by omega)]

lemma fe_e11 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 1)) ∧ (p < 2 * h + 2)) :
    fe h p = 3 * h + 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_pos (show p < 2 * h + 2 by omega)]

lemma fe_e12 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 2)) ∧ (p < 2 * h + 3)) :
    fe h p = h + 4 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_pos (show p < 2 * h + 3 by omega)]

lemma fe_e13 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 3)) ∧ (p < 2 * h + 4)) :
    fe h p = 3 * h + 3 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_pos (show p < 2 * h + 4 by omega)]

lemma fe_e14 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 4)) ∧ (p < 2 * h + 5)) :
    fe h p = h + 3 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_pos (show p < 2 * h + 5 by omega)]

lemma fe_e15 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 5)) ∧ (p + 5 < 4 * h) ∧ ((p - (2 * h + 5)) % 2 = 0)) :
    fe h p = 3 * h + 4 + (p - (2 * h + 5)) / 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_pos (show p + 5 < 4 * h by omega), if_pos (show (p - (2 * h + 5)) % 2 = 0 by omega)]

lemma fe_e16 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 5)) ∧ (p + 5 < 4 * h) ∧ (¬ ((p - (2 * h + 5)) % 2 = 0))) :
    fe h p = 3 * h - 2 - (p - (2 * h + 5)) / 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_pos (show p + 5 < 4 * h by omega), if_neg (show ¬ ((p - (2 * h + 5)) % 2 = 0) by omega)]

lemma fe_e17 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 5 < 4 * h)) ∧ (p + 4 < 4 * h)) :
    fe h p = 4 * h - 1 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_pos (show p + 4 < 4 * h by omega)]

lemma fe_e18 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 4 < 4 * h)) ∧ (p + 3 < 4 * h)) :
    fe h p = 2 * h + 3 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_pos (show p + 3 < 4 * h by omega)]

lemma fe_e19 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 3 < 4 * h)) ∧ (p + 2 < 4 * h)) :
    fe h p = 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_neg (show ¬ (p + 3 < 4 * h) by omega), if_pos (show p + 2 < 4 * h by omega)]

lemma fe_e20 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 2 < 4 * h)) ∧ (p + 1 < 4 * h)) :
    fe h p = 2 * h + 2 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_neg (show ¬ (p + 3 < 4 * h) by omega), if_neg (show ¬ (p + 2 < 4 * h) by omega), if_pos (show p + 1 < 4 * h by omega)]

lemma fe_e21 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 1 < 4 * h))) :
    fe h p = 3 := by
  unfold fe
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_neg (show ¬ (p + 3 < 4 * h) by omega), if_neg (show ¬ (p + 2 < 4 * h) by omega), if_neg (show ¬ (p + 1 < 4 * h) by omega)]

lemma fe_seg {h : ℕ} (p : ℕ) (hh : 6 ≤ h) :
    ((p < 1)) ∨
    ((¬ (p < 1)) ∧ (p < 2)) ∨
    ((¬ (p < 2)) ∧ (p < 3)) ∨
    ((¬ (p < 3)) ∧ (p < 4)) ∨
    ((¬ (p < 4)) ∧ (p < 5)) ∨
    ((¬ (p < 5)) ∧ (p + 3 < 2 * h) ∧ ((p - 5) % 2 = 0)) ∨
    ((¬ (p < 5)) ∧ (p + 3 < 2 * h) ∧ (¬ ((p - 5) % 2 = 0))) ∨
    ((¬ (p + 3 < 2 * h)) ∧ (p + 2 < 2 * h)) ∨
    ((¬ (p + 2 < 2 * h)) ∧ (p + 1 < 2 * h)) ∨
    ((¬ (p + 1 < 2 * h)) ∧ (p < 2 * h)) ∨
    ((¬ (p < 2 * h)) ∧ (p < 2 * h + 1)) ∨
    ((¬ (p < 2 * h + 1)) ∧ (p < 2 * h + 2)) ∨
    ((¬ (p < 2 * h + 2)) ∧ (p < 2 * h + 3)) ∨
    ((¬ (p < 2 * h + 3)) ∧ (p < 2 * h + 4)) ∨
    ((¬ (p < 2 * h + 4)) ∧ (p < 2 * h + 5)) ∨
    ((¬ (p < 2 * h + 5)) ∧ (p + 5 < 4 * h) ∧ ((p - (2 * h + 5)) % 2 = 0)) ∨
    ((¬ (p < 2 * h + 5)) ∧ (p + 5 < 4 * h) ∧ (¬ ((p - (2 * h + 5)) % 2 = 0))) ∨
    ((¬ (p + 5 < 4 * h)) ∧ (p + 4 < 4 * h)) ∨
    ((¬ (p + 4 < 4 * h)) ∧ (p + 3 < 4 * h)) ∨
    ((¬ (p + 3 < 4 * h)) ∧ (p + 2 < 4 * h)) ∨
    ((¬ (p + 2 < 4 * h)) ∧ (p + 1 < 4 * h)) ∨
    ((¬ (p + 1 < 4 * h))) := by
  omega

-- number of pieces of `fe`: 22

def de (h p : ℕ) : ℤ :=
  if p < 1 then 5
  else   if p < 2 then -4
  else   if p < 3 then 3
  else   if p < 4 then 2 * (h : ℤ) - 3
  else   if p < 5 then -(2 * (h : ℤ) - 5)
  else   if p + 4 < 2 * h then (if (p - 5) % 2 = 0 then 2 * (h : ℤ) - 6 - ((p : ℤ) - 5) else -(2 * (h : ℤ) - 6 - ((p : ℤ) - 5)))
  else   if p + 3 < 2 * h then 2 * (h : ℤ) - 4
  else   if p + 2 < 2 * h then -2
  else   if p + 1 < 2 * h then -(2 * (h : ℤ) - 3)
  else   if p < 2 * h then 2 * (h : ℤ) - 2
  else   if p < 2 * h + 1 then 2
  else   if p < 2 * h + 2 then -(2 * (h : ℤ) - 2)
  else   if p < 2 * h + 3 then 2 * (h : ℤ) - 1
  else   if p < 2 * h + 4 then -(2 * (h : ℤ))
  else   if p < 2 * h + 5 then 2 * (h : ℤ) + 1
  else   if p + 6 < 4 * h then (if (p - (2 * h + 5)) % 2 = 0 then -(6 + ((p : ℤ) - (2 * (h : ℤ) + 5))) else 6 + ((p : ℤ) - (2 * (h : ℤ) + 5)))
  else   if p + 5 < 4 * h then 2 * (h : ℤ) - 5
  else   if p + 4 < 4 * h then -(2 * (h : ℤ) - 4)
  else   if p + 3 < 4 * h then -(2 * (h : ℤ) + 1)
  else   if p + 2 < 4 * h then 2 * (h : ℤ)
  else   if p + 1 < 4 * h then -(2 * (h : ℤ) - 1)
  else -3

lemma de_e0 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (p < 1)) :
    de h p = 5 := by
  unfold de
  rw [if_pos (show p < 1 by omega)]

lemma de_e1 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 1)) ∧ (p < 2)) :
    de h p = -4 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_pos (show p < 2 by omega)]

lemma de_e2 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2)) ∧ (p < 3)) :
    de h p = 3 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_pos (show p < 3 by omega)]

lemma de_e3 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 3)) ∧ (p < 4)) :
    de h p = 2 * (h : ℤ) - 3 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_pos (show p < 4 by omega)]

lemma de_e4 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 4)) ∧ (p < 5)) :
    de h p = -(2 * (h : ℤ) - 5) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_pos (show p < 5 by omega)]

lemma de_e5 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 5)) ∧ (p + 4 < 2 * h) ∧ ((p - 5) % 2 = 0)) :
    de h p = 2 * (h : ℤ) - 6 - ((p : ℤ) - 5) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_pos (show p + 4 < 2 * h by omega), if_pos (show (p - 5) % 2 = 0 by omega)]

lemma de_e6 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 5)) ∧ (p + 4 < 2 * h) ∧ (¬ ((p - 5) % 2 = 0))) :
    de h p = -(2 * (h : ℤ) - 6 - ((p : ℤ) - 5)) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_pos (show p + 4 < 2 * h by omega), if_neg (show ¬ ((p - 5) % 2 = 0) by omega)]

lemma de_e7 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 4 < 2 * h)) ∧ (p + 3 < 2 * h)) :
    de h p = 2 * (h : ℤ) - 4 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_pos (show p + 3 < 2 * h by omega)]

lemma de_e8 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 3 < 2 * h)) ∧ (p + 2 < 2 * h)) :
    de h p = -2 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_pos (show p + 2 < 2 * h by omega)]

lemma de_e9 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 2 < 2 * h)) ∧ (p + 1 < 2 * h)) :
    de h p = -(2 * (h : ℤ) - 3) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_pos (show p + 1 < 2 * h by omega)]

lemma de_e10 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 1 < 2 * h)) ∧ (p < 2 * h)) :
    de h p = 2 * (h : ℤ) - 2 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_pos (show p < 2 * h by omega)]

lemma de_e11 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h)) ∧ (p < 2 * h + 1)) :
    de h p = 2 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_pos (show p < 2 * h + 1 by omega)]

lemma de_e12 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 1)) ∧ (p < 2 * h + 2)) :
    de h p = -(2 * (h : ℤ) - 2) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_pos (show p < 2 * h + 2 by omega)]

lemma de_e13 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 2)) ∧ (p < 2 * h + 3)) :
    de h p = 2 * (h : ℤ) - 1 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_pos (show p < 2 * h + 3 by omega)]

lemma de_e14 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 3)) ∧ (p < 2 * h + 4)) :
    de h p = -(2 * (h : ℤ)) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_pos (show p < 2 * h + 4 by omega)]

lemma de_e15 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 4)) ∧ (p < 2 * h + 5)) :
    de h p = 2 * (h : ℤ) + 1 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_pos (show p < 2 * h + 5 by omega)]

lemma de_e16 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 5)) ∧ (p + 6 < 4 * h) ∧ ((p - (2 * h + 5)) % 2 = 0)) :
    de h p = -(6 + ((p : ℤ) - (2 * (h : ℤ) + 5))) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_pos (show p + 6 < 4 * h by omega), if_pos (show (p - (2 * h + 5)) % 2 = 0 by omega)]

lemma de_e17 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p < 2 * h + 5)) ∧ (p + 6 < 4 * h) ∧ (¬ ((p - (2 * h + 5)) % 2 = 0))) :
    de h p = 6 + ((p : ℤ) - (2 * (h : ℤ) + 5)) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_pos (show p + 6 < 4 * h by omega), if_neg (show ¬ ((p - (2 * h + 5)) % 2 = 0) by omega)]

lemma de_e18 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 6 < 4 * h)) ∧ (p + 5 < 4 * h)) :
    de h p = 2 * (h : ℤ) - 5 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 6 < 4 * h) by omega), if_pos (show p + 5 < 4 * h by omega)]

lemma de_e19 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 5 < 4 * h)) ∧ (p + 4 < 4 * h)) :
    de h p = -(2 * (h : ℤ) - 4) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 6 < 4 * h) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_pos (show p + 4 < 4 * h by omega)]

lemma de_e20 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 4 < 4 * h)) ∧ (p + 3 < 4 * h)) :
    de h p = -(2 * (h : ℤ) + 1) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 6 < 4 * h) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_pos (show p + 3 < 4 * h by omega)]

lemma de_e21 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 3 < 4 * h)) ∧ (p + 2 < 4 * h)) :
    de h p = 2 * (h : ℤ) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 6 < 4 * h) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_neg (show ¬ (p + 3 < 4 * h) by omega), if_pos (show p + 2 < 4 * h by omega)]

lemma de_e22 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 2 < 4 * h)) ∧ (p + 1 < 4 * h)) :
    de h p = -(2 * (h : ℤ) - 1) := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 6 < 4 * h) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_neg (show ¬ (p + 3 < 4 * h) by omega), if_neg (show ¬ (p + 2 < 4 * h) by omega), if_pos (show p + 1 < 4 * h by omega)]

lemma de_e23 {h : ℕ} (p : ℕ) (hh : 6 ≤ h) (hs : (¬ (p + 1 < 4 * h))) :
    de h p = -3 := by
  unfold de
  rw [if_neg (show ¬ (p < 1) by omega), if_neg (show ¬ (p < 2) by omega), if_neg (show ¬ (p < 3) by omega), if_neg (show ¬ (p < 4) by omega), if_neg (show ¬ (p < 5) by omega), if_neg (show ¬ (p + 4 < 2 * h) by omega), if_neg (show ¬ (p + 3 < 2 * h) by omega), if_neg (show ¬ (p + 2 < 2 * h) by omega), if_neg (show ¬ (p + 1 < 2 * h) by omega), if_neg (show ¬ (p < 2 * h) by omega), if_neg (show ¬ (p < 2 * h + 1) by omega), if_neg (show ¬ (p < 2 * h + 2) by omega), if_neg (show ¬ (p < 2 * h + 3) by omega), if_neg (show ¬ (p < 2 * h + 4) by omega), if_neg (show ¬ (p < 2 * h + 5) by omega), if_neg (show ¬ (p + 6 < 4 * h) by omega), if_neg (show ¬ (p + 5 < 4 * h) by omega), if_neg (show ¬ (p + 4 < 4 * h) by omega), if_neg (show ¬ (p + 3 < 4 * h) by omega), if_neg (show ¬ (p + 2 < 4 * h) by omega), if_neg (show ¬ (p + 1 < 4 * h) by omega)]

lemma de_seg {h : ℕ} (p : ℕ) (hh : 6 ≤ h) :
    ((p < 1)) ∨
    ((¬ (p < 1)) ∧ (p < 2)) ∨
    ((¬ (p < 2)) ∧ (p < 3)) ∨
    ((¬ (p < 3)) ∧ (p < 4)) ∨
    ((¬ (p < 4)) ∧ (p < 5)) ∨
    ((¬ (p < 5)) ∧ (p + 4 < 2 * h) ∧ ((p - 5) % 2 = 0)) ∨
    ((¬ (p < 5)) ∧ (p + 4 < 2 * h) ∧ (¬ ((p - 5) % 2 = 0))) ∨
    ((¬ (p + 4 < 2 * h)) ∧ (p + 3 < 2 * h)) ∨
    ((¬ (p + 3 < 2 * h)) ∧ (p + 2 < 2 * h)) ∨
    ((¬ (p + 2 < 2 * h)) ∧ (p + 1 < 2 * h)) ∨
    ((¬ (p + 1 < 2 * h)) ∧ (p < 2 * h)) ∨
    ((¬ (p < 2 * h)) ∧ (p < 2 * h + 1)) ∨
    ((¬ (p < 2 * h + 1)) ∧ (p < 2 * h + 2)) ∨
    ((¬ (p < 2 * h + 2)) ∧ (p < 2 * h + 3)) ∨
    ((¬ (p < 2 * h + 3)) ∧ (p < 2 * h + 4)) ∨
    ((¬ (p < 2 * h + 4)) ∧ (p < 2 * h + 5)) ∨
    ((¬ (p < 2 * h + 5)) ∧ (p + 6 < 4 * h) ∧ ((p - (2 * h + 5)) % 2 = 0)) ∨
    ((¬ (p < 2 * h + 5)) ∧ (p + 6 < 4 * h) ∧ (¬ ((p - (2 * h + 5)) % 2 = 0))) ∨
    ((¬ (p + 6 < 4 * h)) ∧ (p + 5 < 4 * h)) ∨
    ((¬ (p + 5 < 4 * h)) ∧ (p + 4 < 4 * h)) ∨
    ((¬ (p + 4 < 4 * h)) ∧ (p + 3 < 4 * h)) ∨
    ((¬ (p + 3 < 4 * h)) ∧ (p + 2 < 4 * h)) ∨
    ((¬ (p + 2 < 4 * h)) ∧ (p + 1 < 4 * h)) ∨
    ((¬ (p + 1 < 4 * h))) := by
  omega

-- number of pieces of `de`: 24

set_option maxHeartbeats 8000000 in
lemma fe_lt {h p : ℕ} (hh : 6 ≤ h) (hp : p < 4 * h) : fe h p < 4 * h := by
  rcases fe_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> (first | rw [fe_e0 p hh hs] | rw [fe_e1 p hh hs] | rw [fe_e2 p hh hs] | rw [fe_e3 p hh hs] | rw [fe_e4 p hh hs] | rw [fe_e5 p hh hs] | rw [fe_e6 p hh hs] | rw [fe_e7 p hh hs] | rw [fe_e8 p hh hs] | rw [fe_e9 p hh hs] | rw [fe_e10 p hh hs] | rw [fe_e11 p hh hs] | rw [fe_e12 p hh hs] | rw [fe_e13 p hh hs] | rw [fe_e14 p hh hs] | rw [fe_e15 p hh hs] | rw [fe_e16 p hh hs] | rw [fe_e17 p hh hs] | rw [fe_e18 p hh hs] | rw [fe_e19 p hh hs] | rw [fe_e20 p hh hs] | rw [fe_e21 p hh hs]) <;> omega

set_option maxHeartbeats 8000000 in
lemma fe_inj {h p q : ℕ} (hh : 6 ≤ h) (hp : p < 4 * h) (hq : q < 4 * h)
    (he : fe h p = fe h q) : p = q := by
  rcases fe_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> rcases fe_seg q hh with ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht <;>
  (first | rw [fe_e0 p hh hs] at he | rw [fe_e1 p hh hs] at he | rw [fe_e2 p hh hs] at he | rw [fe_e3 p hh hs] at he | rw [fe_e4 p hh hs] at he | rw [fe_e5 p hh hs] at he | rw [fe_e6 p hh hs] at he | rw [fe_e7 p hh hs] at he | rw [fe_e8 p hh hs] at he | rw [fe_e9 p hh hs] at he | rw [fe_e10 p hh hs] at he | rw [fe_e11 p hh hs] at he | rw [fe_e12 p hh hs] at he | rw [fe_e13 p hh hs] at he | rw [fe_e14 p hh hs] at he | rw [fe_e15 p hh hs] at he | rw [fe_e16 p hh hs] at he | rw [fe_e17 p hh hs] at he | rw [fe_e18 p hh hs] at he | rw [fe_e19 p hh hs] at he | rw [fe_e20 p hh hs] at he | rw [fe_e21 p hh hs] at he) <;>
  (first | rw [fe_e0 q hh ht] at he | rw [fe_e1 q hh ht] at he | rw [fe_e2 q hh ht] at he | rw [fe_e3 q hh ht] at he | rw [fe_e4 q hh ht] at he | rw [fe_e5 q hh ht] at he | rw [fe_e6 q hh ht] at he | rw [fe_e7 q hh ht] at he | rw [fe_e8 q hh ht] at he | rw [fe_e9 q hh ht] at he | rw [fe_e10 q hh ht] at he | rw [fe_e11 q hh ht] at he | rw [fe_e12 q hh ht] at he | rw [fe_e13 q hh ht] at he | rw [fe_e14 q hh ht] at he | rw [fe_e15 q hh ht] at he | rw [fe_e16 q hh ht] at he | rw [fe_e17 q hh ht] at he | rw [fe_e18 q hh ht] at he | rw [fe_e19 q hh ht] at he | rw [fe_e20 q hh ht] at he | rw [fe_e21 q hh ht] at he) <;> omega

set_option maxHeartbeats 8000000 in
lemma de_range {h p : ℕ} (hh : 6 ≤ h) (hp : p < 4 * h) :
    (2 ≤ de h p ∧ de h p ≤ 2 * (h : ℤ) + 1) ∨ (-(2 * (h : ℤ) + 1) ≤ de h p ∧ de h p ≤ -2) := by
  rcases de_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> (first | rw [de_e0 p hh hs] | rw [de_e1 p hh hs] | rw [de_e2 p hh hs] | rw [de_e3 p hh hs] | rw [de_e4 p hh hs] | rw [de_e5 p hh hs] | rw [de_e6 p hh hs] | rw [de_e7 p hh hs] | rw [de_e8 p hh hs] | rw [de_e9 p hh hs] | rw [de_e10 p hh hs] | rw [de_e11 p hh hs] | rw [de_e12 p hh hs] | rw [de_e13 p hh hs] | rw [de_e14 p hh hs] | rw [de_e15 p hh hs] | rw [de_e16 p hh hs] | rw [de_e17 p hh hs] | rw [de_e18 p hh hs] | rw [de_e19 p hh hs] | rw [de_e20 p hh hs] | rw [de_e21 p hh hs] | rw [de_e22 p hh hs] | rw [de_e23 p hh hs]) <;> omega

set_option maxHeartbeats 8000000 in
lemma de_inj {h p q : ℕ} (hh : 6 ≤ h) (hp : p < 4 * h) (hq : q < 4 * h)
    (he : de h p = de h q) : p = q := by
  rcases de_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> rcases de_seg q hh with ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht | ht <;>
  (first | rw [de_e0 p hh hs] at he | rw [de_e1 p hh hs] at he | rw [de_e2 p hh hs] at he | rw [de_e3 p hh hs] at he | rw [de_e4 p hh hs] at he | rw [de_e5 p hh hs] at he | rw [de_e6 p hh hs] at he | rw [de_e7 p hh hs] at he | rw [de_e8 p hh hs] at he | rw [de_e9 p hh hs] at he | rw [de_e10 p hh hs] at he | rw [de_e11 p hh hs] at he | rw [de_e12 p hh hs] at he | rw [de_e13 p hh hs] at he | rw [de_e14 p hh hs] at he | rw [de_e15 p hh hs] at he | rw [de_e16 p hh hs] at he | rw [de_e17 p hh hs] at he | rw [de_e18 p hh hs] at he | rw [de_e19 p hh hs] at he | rw [de_e20 p hh hs] at he | rw [de_e21 p hh hs] at he | rw [de_e22 p hh hs] at he | rw [de_e23 p hh hs] at he) <;>
  (first | rw [de_e0 q hh ht] at he | rw [de_e1 q hh ht] at he | rw [de_e2 q hh ht] at he | rw [de_e3 q hh ht] at he | rw [de_e4 q hh ht] at he | rw [de_e5 q hh ht] at he | rw [de_e6 q hh ht] at he | rw [de_e7 q hh ht] at he | rw [de_e8 q hh ht] at he | rw [de_e9 q hh ht] at he | rw [de_e10 q hh ht] at he | rw [de_e11 q hh ht] at he | rw [de_e12 q hh ht] at he | rw [de_e13 q hh ht] at he | rw [de_e14 q hh ht] at he | rw [de_e15 q hh ht] at he | rw [de_e16 q hh ht] at he | rw [de_e17 q hh ht] at he | rw [de_e18 q hh ht] at he | rw [de_e19 q hh ht] at he | rw [de_e20 q hh ht] at he | rw [de_e21 q hh ht] at he | rw [de_e22 q hh ht] at he | rw [de_e23 q hh ht] at he) <;> omega

set_option maxHeartbeats 8000000 in
lemma fe_step {h p : ℕ} (hh : 6 ≤ h) (hp : p + 1 < 4 * h) :
    (fe h (p + 1) : ℤ) = fe h p + de h p := by
  rcases de_seg p hh with hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs | hs <;> (first | rw [de_e0 p hh hs] | rw [de_e1 p hh hs] | rw [de_e2 p hh hs] | rw [de_e3 p hh hs] | rw [de_e4 p hh hs] | rw [de_e5 p hh hs] | rw [de_e6 p hh hs] | rw [de_e7 p hh hs] | rw [de_e8 p hh hs] | rw [de_e9 p hh hs] | rw [de_e10 p hh hs] | rw [de_e11 p hh hs] | rw [de_e12 p hh hs] | rw [de_e13 p hh hs] | rw [de_e14 p hh hs] | rw [de_e15 p hh hs] | rw [de_e16 p hh hs] | rw [de_e17 p hh hs] | rw [de_e18 p hh hs] | rw [de_e19 p hh hs] | rw [de_e20 p hh hs] | rw [de_e21 p hh hs] | rw [de_e22 p hh hs] | rw [de_e23 p hh hs]) <;>
  (first | rw [fe_e0 p hh (by omega)] | rw [fe_e1 p hh (by omega)] | rw [fe_e2 p hh (by omega)] | rw [fe_e3 p hh (by omega)] | rw [fe_e4 p hh (by omega)] | rw [fe_e5 p hh (by omega)] | rw [fe_e6 p hh (by omega)] | rw [fe_e7 p hh (by omega)] | rw [fe_e8 p hh (by omega)] | rw [fe_e9 p hh (by omega)] | rw [fe_e10 p hh (by omega)] | rw [fe_e11 p hh (by omega)] | rw [fe_e12 p hh (by omega)] | rw [fe_e13 p hh (by omega)] | rw [fe_e14 p hh (by omega)] | rw [fe_e15 p hh (by omega)] | rw [fe_e16 p hh (by omega)] | rw [fe_e17 p hh (by omega)] | rw [fe_e18 p hh (by omega)] | rw [fe_e19 p hh (by omega)] | rw [fe_e20 p hh (by omega)] | rw [fe_e21 p hh (by omega)]) <;>
  (first | rw [fe_e0 (p + 1) hh (by omega)] | rw [fe_e1 (p + 1) hh (by omega)] | rw [fe_e2 (p + 1) hh (by omega)] | rw [fe_e3 (p + 1) hh (by omega)] | rw [fe_e4 (p + 1) hh (by omega)] | rw [fe_e5 (p + 1) hh (by omega)] | rw [fe_e6 (p + 1) hh (by omega)] | rw [fe_e7 (p + 1) hh (by omega)] | rw [fe_e8 (p + 1) hh (by omega)] | rw [fe_e9 (p + 1) hh (by omega)] | rw [fe_e10 (p + 1) hh (by omega)] | rw [fe_e11 (p + 1) hh (by omega)] | rw [fe_e12 (p + 1) hh (by omega)] | rw [fe_e13 (p + 1) hh (by omega)] | rw [fe_e14 (p + 1) hh (by omega)] | rw [fe_e15 (p + 1) hh (by omega)] | rw [fe_e16 (p + 1) hh (by omega)] | rw [fe_e17 (p + 1) hh (by omega)] | rw [fe_e18 (p + 1) hh (by omega)] | rw [fe_e19 (p + 1) hh (by omega)] | rw [fe_e20 (p + 1) hh (by omega)] | rw [fe_e21 (p + 1) hh (by omega)]) <;> omega

set_option maxHeartbeats 8000000 in
lemma fe_last {h : ℕ} (hh : 6 ≤ h) :
    (fe h 0 : ℤ) = fe h (4 * h - 1) + de h (4 * h - 1) := by
  (first | rw [de_e0 (4 * h - 1) hh (by omega)] | rw [de_e1 (4 * h - 1) hh (by omega)] | rw [de_e2 (4 * h - 1) hh (by omega)] | rw [de_e3 (4 * h - 1) hh (by omega)] | rw [de_e4 (4 * h - 1) hh (by omega)] | rw [de_e5 (4 * h - 1) hh (by omega)] | rw [de_e6 (4 * h - 1) hh (by omega)] | rw [de_e7 (4 * h - 1) hh (by omega)] | rw [de_e8 (4 * h - 1) hh (by omega)] | rw [de_e9 (4 * h - 1) hh (by omega)] | rw [de_e10 (4 * h - 1) hh (by omega)] | rw [de_e11 (4 * h - 1) hh (by omega)] | rw [de_e12 (4 * h - 1) hh (by omega)] | rw [de_e13 (4 * h - 1) hh (by omega)] | rw [de_e14 (4 * h - 1) hh (by omega)] | rw [de_e15 (4 * h - 1) hh (by omega)] | rw [de_e16 (4 * h - 1) hh (by omega)] | rw [de_e17 (4 * h - 1) hh (by omega)] | rw [de_e18 (4 * h - 1) hh (by omega)] | rw [de_e19 (4 * h - 1) hh (by omega)] | rw [de_e20 (4 * h - 1) hh (by omega)] | rw [de_e21 (4 * h - 1) hh (by omega)] | rw [de_e22 (4 * h - 1) hh (by omega)] | rw [de_e23 (4 * h - 1) hh (by omega)])
  (first | rw [fe_e0 0 hh (by omega)] | rw [fe_e1 0 hh (by omega)] | rw [fe_e2 0 hh (by omega)] | rw [fe_e3 0 hh (by omega)] | rw [fe_e4 0 hh (by omega)] | rw [fe_e5 0 hh (by omega)] | rw [fe_e6 0 hh (by omega)] | rw [fe_e7 0 hh (by omega)] | rw [fe_e8 0 hh (by omega)] | rw [fe_e9 0 hh (by omega)] | rw [fe_e10 0 hh (by omega)] | rw [fe_e11 0 hh (by omega)] | rw [fe_e12 0 hh (by omega)] | rw [fe_e13 0 hh (by omega)] | rw [fe_e14 0 hh (by omega)] | rw [fe_e15 0 hh (by omega)] | rw [fe_e16 0 hh (by omega)] | rw [fe_e17 0 hh (by omega)] | rw [fe_e18 0 hh (by omega)] | rw [fe_e19 0 hh (by omega)] | rw [fe_e20 0 hh (by omega)] | rw [fe_e21 0 hh (by omega)])
  (first | rw [fe_e0 (4 * h - 1) hh (by omega)] | rw [fe_e1 (4 * h - 1) hh (by omega)] | rw [fe_e2 (4 * h - 1) hh (by omega)] | rw [fe_e3 (4 * h - 1) hh (by omega)] | rw [fe_e4 (4 * h - 1) hh (by omega)] | rw [fe_e5 (4 * h - 1) hh (by omega)] | rw [fe_e6 (4 * h - 1) hh (by omega)] | rw [fe_e7 (4 * h - 1) hh (by omega)] | rw [fe_e8 (4 * h - 1) hh (by omega)] | rw [fe_e9 (4 * h - 1) hh (by omega)] | rw [fe_e10 (4 * h - 1) hh (by omega)] | rw [fe_e11 (4 * h - 1) hh (by omega)] | rw [fe_e12 (4 * h - 1) hh (by omega)] | rw [fe_e13 (4 * h - 1) hh (by omega)] | rw [fe_e14 (4 * h - 1) hh (by omega)] | rw [fe_e15 (4 * h - 1) hh (by omega)] | rw [fe_e16 (4 * h - 1) hh (by omega)] | rw [fe_e17 (4 * h - 1) hh (by omega)] | rw [fe_e18 (4 * h - 1) hh (by omega)] | rw [fe_e19 (4 * h - 1) hh (by omega)] | rw [fe_e20 (4 * h - 1) hh (by omega)] | rw [fe_e21 (4 * h - 1) hh (by omega)])
  omega

end GrahamPM
