# Generates GrahamPM/CycleEvenGen.lean and GrahamPM/CycleOddGen.lean (run from the `lean/` folder:
#   python3 scripts/gen_cycle.py).
# Each function (vertex at position p, jump at position p) is a chain of threshold conditions
# (additive form, no natural-number subtraction in the conditions); zigzag pieces additionally split
# by parity. For every piece k: an evaluation lemma (proved only by `rw` with `if_pos`/`if_neg`, each
# condition by `omega`), plus a case-split lemma (`omega`) and the main lemmas by case analysis +
# `omega`. The generator need not be trusted: Lean checks the generated proofs.
import sys
NSEG = {}
MAIN = {}

def build(name, par, conds, vals, nat):
    """conds: list of threshold conditions (strings in p, par); vals: list of values, each either an
    expression or (parity condition, value_if, value_else). The last value is the else branch."""
    assert len(vals) == len(conds) + 1
    ty = "ℕ" if nat else "ℤ"
    # definition
    lines = [f"def {name} ({par} p : ℕ) : {ty} :="]
    body = ""
    for c, v in zip(conds, vals[:-1]):
        body += f"  if {c} then {vexpr(v)}\n  else "
    body += vexpr(vals[-1])
    lines.append(body)
    # pieces
    segs = []      # (list of conditions as strings, value, list of (if_pos/if_neg, condition))
    for k, v in enumerate(vals):
        pre = [("if_neg", conds[j]) for j in range(k)]
        here = [("if_pos", conds[k])] if k < len(conds) else []
        hyps = [f"¬ ({conds[j]})" for j in ([k - 1] if k > 0 else [])] + ([conds[k]] if k < len(conds) else [])
        if isinstance(v, tuple):
            pc, va, vb = v
            segs.append((hyps + [pc], va, pre + here + [("if_pos", pc)]))
            segs.append((hyps + [f"¬ ({pc})"], vb, pre + here + [("if_neg", pc)]))
        else:
            segs.append((hyps, v, pre + here))
    return "\n".join(lines), segs

def vexpr(v):
    if isinstance(v, tuple):
        pc, va, vb = v
        return f"(if {pc} then {va} else {vb})"
    return v

def emit(fname, ns, defs):
    out = ["import Mathlib", "", f"/-! Generated by `scripts/gen_cycle.py`; do not edit by hand. -/", "",
           "set_option linter.unusedVariables false", "set_option linter.deprecated false", "",
           "namespace GrahamPM", ""]
    for (name, par, hyp, conds, vals, nat) in defs:
        d, segs = build(name, par, conds, vals, nat)
        out.append(d); out.append("")
        for k, (hyps, v, rws) in enumerate(segs):
            hs = " ∧ ".join(f"({x})" for x in hyps) if hyps else "True"
            rwl = ", ".join(f"{a} (show {('¬ (' + c + ')') if a == 'if_neg' else c} by omega)" for a, c in rws)
            out.append(f"lemma {name}_e{k} {{{par} : ℕ}} (p : ℕ) (hh : {hyp}) (hs : {hs}) :\n"
                       f"    {name} {par} p = {v} := by\n  unfold {name}\n  rw [{rwl}]\n")
        alts = " ∨\n    ".join("(" + (" ∧ ".join(f"({x})" for x in hyps) if hyps else "True") + ")" for hyps, _, _ in segs)
        out.append(f"lemma {name}_seg {{{par} : ℕ}} (p : ℕ) (hh : {hyp}) :\n    {alts} := by\n  omega\n")
        out.append(f"-- number of pieces of `{name}`: {len(segs)}\n")
        NSEG[name] = len(segs)
    out += MAIN.get(fname, [])
    out.append("end GrahamPM\n")
    open(fname, "w").write("\n".join(out))

# ---------- even r = 2h: fe = vertex at position p, de = jump at position p ----------
fe_conds = ["p < 1", "p < 2", "p < 3", "p < 4", "p < 5", "p + 3 < 2 * h", "p + 2 < 2 * h", "p + 1 < 2 * h",
            "p < 2 * h", "p < 2 * h + 1", "p < 2 * h + 2", "p < 2 * h + 3", "p < 2 * h + 4", "p < 2 * h + 5",
            "p + 5 < 4 * h", "p + 4 < 4 * h", "p + 3 < 4 * h", "p + 2 < 4 * h", "p + 1 < 4 * h"]
fe_vals = ["0", "5", "1", "4", "2 * h + 1",
           ("(p - 5) % 2 = 0", "6 + (p - 5) / 2", "2 * h - (p - 5) / 2"),
           "3 * h + 1", "3 * h - 1", "h + 2", "3 * h", "3 * h + 2", "h + 4", "3 * h + 3", "h + 3",
           ("(p - (2 * h + 5)) % 2 = 0", "3 * h + 4 + (p - (2 * h + 5)) / 2", "3 * h - 2 - (p - (2 * h + 5)) / 2"),
           "4 * h - 1", "2 * h + 3", "2", "2 * h + 2", "3"]
H = "(h : ℤ)"; P = "(p : ℤ)"
de_conds = ["p < 1", "p < 2", "p < 3", "p < 4", "p < 5", "p + 4 < 2 * h", "p + 3 < 2 * h", "p + 2 < 2 * h",
            "p + 1 < 2 * h", "p < 2 * h", "p < 2 * h + 1", "p < 2 * h + 2", "p < 2 * h + 3", "p < 2 * h + 4",
            "p < 2 * h + 5", "p + 6 < 4 * h", "p + 5 < 4 * h", "p + 4 < 4 * h", "p + 3 < 4 * h", "p + 2 < 4 * h",
            "p + 1 < 4 * h"]
de_vals = ["5", "-4", "3", f"2 * {H} - 3", f"-(2 * {H} - 5)",
           ("(p - 5) % 2 = 0", f"2 * {H} - 6 - ({P} - 5)", f"-(2 * {H} - 6 - ({P} - 5))"),
           f"2 * {H} - 4", "-2", f"-(2 * {H} - 3)", f"2 * {H} - 2", "2", f"-(2 * {H} - 2)", f"2 * {H} - 1",
           f"-(2 * {H})", f"2 * {H} + 1",
           ("(p - (2 * h + 5)) % 2 = 0", f"-(6 + ({P} - (2 * {H} + 5)))", f"6 + ({P} - (2 * {H} + 5))"),
           f"2 * {H} - 5", f"-(2 * {H} - 4)", f"-(2 * {H} + 1)", f"2 * {H}", f"-(2 * {H} - 1)", "-3"]
def ors(n): return " | ".join(["hs"] * n)
def firsts(name, n, arg, hyp, h):
    return "(first " + " ".join(f"| rw [{name}_e{k} {arg} {h} {hyp}]" for k in range(n)) + ")"
def firsts_at(name, n, arg, hyp, h, tgt):
    return "(first " + " ".join(f"| rw [{name}_e{k} {arg} {h} {hyp}] at {tgt}" for k in range(n)) + ")"
def main_lemmas(f, d, par, hyp, nlen, nf, nd):
    n = nlen
    L = []
    L.append(f"lemma {f}_lt {{{par} p : ℕ}} (hh : {hyp}) (hp : p < {n}) : {f} {par} p < {n} := by\n"
             f"  rcases {f}_seg p hh with {ors(nf)} <;> {firsts(f, nf, 'p', 'hs', 'hh')} <;> omega\n")
    L.append(f"lemma {f}_inj {{{par} p q : ℕ}} (hh : {hyp}) (hp : p < {n}) (hq : q < {n})\n"
             f"    (he : {f} {par} p = {f} {par} q) : p = q := by\n"
             f"  rcases {f}_seg p hh with {ors(nf)} <;> rcases {f}_seg q hh with {ors(nf).replace('hs', 'ht')} <;>\n"
             f"  {firsts_at(f, nf, 'p', 'hs', 'hh', 'he')} <;>\n  {firsts_at(f, nf, 'q', 'ht', 'hh', 'he')} <;> omega\n")
    L.append(f"lemma {d}_range {{{par} p : ℕ}} (hh : {hyp}) (hp : p < {n}) :\n"
             f"    (2 ≤ {d} {par} p ∧ {d} {par} p ≤ RMAX) ∨ (-(RMAX) ≤ {d} {par} p ∧ {d} {par} p ≤ -2) := by\n"
             f"  rcases {d}_seg p hh with {ors(nd)} <;> {firsts(d, nd, 'p', 'hs', 'hh')} <;> omega\n")
    L.append(f"lemma {d}_inj {{{par} p q : ℕ}} (hh : {hyp}) (hp : p < {n}) (hq : q < {n})\n"
             f"    (he : {d} {par} p = {d} {par} q) : p = q := by\n"
             f"  rcases {d}_seg p hh with {ors(nd)} <;> rcases {d}_seg q hh with {ors(nd).replace('hs', 'ht')} <;>\n"
             f"  {firsts_at(d, nd, 'p', 'hs', 'hh', 'he')} <;>\n  {firsts_at(d, nd, 'q', 'ht', 'hh', 'he')} <;> omega\n")
    L.append(f"lemma {f}_step {{{par} p : ℕ}} (hh : {hyp}) (hp : p + 1 < {n}) :\n"
             f"    ({f} {par} (p + 1) : ℤ) = {f} {par} p + {d} {par} p := by\n"
             f"  rcases {d}_seg p hh with {ors(nd)} <;> {firsts(d, nd, 'p', 'hs', 'hh')} <;>\n"
             f"  {firsts(f, nf, 'p', '(by omega)', 'hh')} <;>\n  {firsts(f, nf, '(p + 1)', '(by omega)', 'hh')} <;> omega\n")
    L.append(f"lemma {f}_last {{{par} : ℕ}} (hh : {hyp}) :\n"
             f"    ({f} {par} 0 : ℤ) = {f} {par} ({n} - 1) + {d} {par} ({n} - 1) := by\n"
             f"  {firsts(d, nd, '(' + n + ' - 1)', '(by omega)', 'hh')}\n"
             f"  {firsts(f, nf, '0', '(by omega)', 'hh')}\n"
             f"  {firsts(f, nf, '(' + n + ' - 1)', '(by omega)', 'hh')}\n  omega\n")
    return ["set_option maxHeartbeats 8000000 in\n" + x for x in L]
MAIN["GrahamPM/CycleEvenGen.lean"] = [x.replace("RMAX", "2 * (h : ℤ) + 1") for x in
    main_lemmas("fe", "de", "h", "6 ≤ h", "4 * h", 22, 24)]
MAIN["GrahamPM/CycleOddGen.lean"] = [x.replace("RMAX", "2 * (s : ℤ) + 2") for x in
    main_lemmas("fo", "dso", "s", "5 ≤ s", "4 * s + 2", 20, 22)]
emit("GrahamPM/CycleEvenGen.lean", "GrahamPM",
     [("fe", "h", "6 ≤ h", fe_conds, fe_vals, True), ("de", "h", "6 ≤ h", de_conds, de_vals, False)])

# ---------- odd r = 2s+1: fo = vertex, dso = jump ----------
fo_conds = ["p < 1", "p < 2", "p + 6 < 2 * s"] + [f"p < 2 * s - 5 + {j}" for j in range(8)] + \
           ["p + 4 < 4 * s"] + [f"p < 4 * s - 3 + {j}" for j in range(5)]
fo_vals = ["0", "2 * s + 2", ("(p - 2) % 2 = 0", "6 + (p - 2) / 2", "2 * s + 1 - (p - 2) / 2"),
           "s + 4", "3 * s + 4", "s + 2", "3 * s + 3", "s + 5", "3 * s + 2", "s + 3", "3 * s + 1",
           ("(p - (2 * s + 2)) % 2 = 0", "3 * s + 5 + (p - (2 * s + 2)) / 2", "3 * s - (p - (2 * s + 2)) / 2"),
           "4", "2 * s + 3", "2", "5", "1", "3"]
S = "(s : ℤ)"
do_conds = ["p < 1", "p < 2", "p + 7 < 2 * s", "p + 6 < 2 * s"] + [f"p < 2 * s - 5 + {j}" for j in range(7)] + \
           ["p < 2 * s + 2", "p + 5 < 4 * s"] + [f"p < 4 * s - 4 + {j}" for j in range(6)]
do_vals = [f"2 * {S} + 2", f"-(2 * {S} - 4)",
           ("(p - 2) % 2 = 0", f"2 * {S} - 5 - ({P} - 2)", f"-(2 * {S} - 5 - ({P} - 2))"),
           "-2", f"2 * {S}", f"-(2 * {S} + 2)", f"2 * {S} + 1", f"-(2 * {S} - 2)", f"2 * {S} - 3",
           f"-(2 * {S} - 1)", f"2 * {S} - 2", "4",
           ("(p - (2 * s + 2)) % 2 = 0", f"-(5 + ({P} - (2 * {S} + 2)))", f"5 + ({P} - (2 * {S} + 2))"),
           f"-(2 * {S})", f"2 * {S} - 1", f"-(2 * {S} + 1)", "3", "-4", "2", "-3"]
emit("GrahamPM/CycleOddGen.lean", "GrahamPM",
     [("fo", "s", "5 ≤ s", fo_conds, fo_vals, True), ("dso", "s", "5 ≤ s", do_conds, do_vals, False)])
assert NSEG == {"fe": 22, "de": 24, "fo": 20, "dso": 22}, NSEG
print("written", NSEG)
